# EMIBA Quick encoding guide

In [1]:
import pandas as pd
import numpy as np

In [2]:
example = {'ITEM': ['Item 1','Item 2','Item 3','Item 4'],
        'CATEGORY': ['A','C','A','B'],
        'PRICE': [12,2,14,8]
        }

df = pd.DataFrame(example, columns = ['ITEM', 'CATEGORY','PRICE'])

df

     ITEM CATEGORY  PRICE
0  Item 1        A     12
1  Item 2        C      2
2  Item 3        A     14
3  Item 4        B      8

In [3]:
df.dtypes

ITEM        object
CATEGORY    object
PRICE        int64
dtype: object

### Approach 1: Label encoding

First approach to encoding categorical values is to use a technique called label encoding. Label encoding is simply converting each value in a column to a number. For example, the CATEGORY column contains 3 different values. We could choose to encode it like this:

A -> 0  
B -> 1  
C -> 2

In [4]:
obj_df = df.select_dtypes(include=['object']).copy()
obj_df.head()

     ITEM CATEGORY
0  Item 1        A
1  Item 2        C
2  Item 3        A
3  Item 4        B

In [9]:
desired_order = ['B','A','C']

In [10]:
obj_df["CATEGORY"] = pd.Categorical(obj_df['CATEGORY'], categories = desired_order, ordered = True)

In [11]:
obj_df.dtypes

ITEM          object
CATEGORY    category
NEW_CAT         int8
dtype: object

In [12]:
obj_df["NEW_CAT"] = obj_df["CATEGORY"].cat.codes
obj_df.head()

     ITEM CATEGORY  NEW_CAT
0  Item 1        A        1
1  Item 2        C        2
2  Item 3        A        1
3  Item 4        B        0

### Approach 2: One hot encoding

Label encoding has the advantage that it is straightforward but it has the disadvantage that the numeric values can be “misinterpreted” by the algorithms. For example, the value of 0 is obviously less than the value of 4 but does that really correspond to the data set in real life?

A common alternative approach is called one hot encoding (but also goes by several different names shown below). Despite the different names, the basic strategy is to convert each category value into a new column and assigns a 1 or 0 (True/False) value to the column. This has the benefit of not weighting a value improperly but does have the downside of adding more columns to the data set.

In [8]:
obj_df = df.select_dtypes(include=['object']).copy()
obj_df.head()

     ITEM CATEGORY
0  Item 1        A
1  Item 2        C
2  Item 3        A
3  Item 4        B

In [9]:
pd.get_dummies(obj_df, columns=["CATEGORY"])

     ITEM  CATEGORY_A  CATEGORY_B  CATEGORY_C
0  Item 1           1           0           0
1  Item 2           0           0           1
2  Item 3           1           0           0
3  Item 4           0           1           0

### Approach 3: Custom binary encoding

Depending on the data set, you may be able to use some combination of label encoding and one hot encoding to create a binary column that meets your needs for further analysis.

In [35]:
obj_df = df.select_dtypes(include=['object']).copy()
obj_df.head()

     ITEM CATEGORY
0  Item 1        A
1  Item 2        C
2  Item 3        A
3  Item 4        B

In [36]:
obj_df['CATEGORY_NEW'] = np.where(obj_df['CATEGORY'].str.contains('A'),1,0)

In [37]:
obj_df.head()

     ITEM CATEGORY  CATEGORY_NEW
0  Item 1        A             1
1  Item 2        C             0
2  Item 3        A             1
3  Item 4        B             0